### ISSUE TITLE
How to convert my Custom Level Object into a Karlson Map?

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [Jor02/KarlsonLevelImporter#6]

**Comment by Jor02** [comment]
You can build assets bundles by using the context menu in the project window.
![image](https://user-images.githubusercontent.com/43887690/129393344-eaaf7639-adde-43e1-aeae-dff30eab49ad.png)

**Comment by Just-a-Unity-Dev** [comment]
Do I build the in the outside directory or the directory with the level object?
