### ISSUE TITLE
Adding a License 

### ISSUE THREAD

**Issue by 64BitDev** [Jor02/KarlsonLevelImporter#8]
Hi Jor02
i would recommend you add a License like the [MIT License](https://opensource.org/license/mit) because Without a license, it’s unclear how others can use or contribute to your project. and slows down development 

This would help me and others in the community feel more comfortable using and contributing to your work.
Thanks for your consideration! 

# Step-by-Step Guide to Adding an MIT License to Your GitHub Repo

## Step 1: Open Your GitHub Repository
1. Navigate to your GitHub account.
2. Go to the repository where you want to add the license.
   - If you’re not in the correct repository, click on the **Repositories** tab and select the right one.

---

## Step 2: Create a New File for the License
1. In the repository view, click the **Add file** button (usually at the top-right).
2. From the dropdown menu, select **Create new file**.

---

## Step 3: Name the File
1. In the file name field, type `LICENSE`.  
   - **Important**: The filename must be exactly `LICENSE` (no extension).

---

## Step 4: Add the MIT License Text
1. Visit the [MIT License template](https://opensource.org/licenses/MIT).
2. Copy the full license text and paste it into the `LICENSE` file.
   - Example:
     ```text
     MIT License
     Copyright 2024 Jor02

     Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.



---

## Step 5: Commit the License
1. Scroll down to the **Commit new file** section.
2. In the **Commit message** box, type:
   ```text
   Add MIT License

**Comment by Jor02** [comment]
Oh oops, I normally add a MIT license to my repo's. Seems like I completely forgot to do that here. Thanks for reminding me.
